#!/usr/bin/env bash
set -euo pipefail

TIMESTAMP=$(date +%s)
JOB_NAME=${JOB_NAME:-gpt_oss_reasoning_full_single_node}
OUTPUT_ROOT=${OUTPUT_ROOT:-/mnt/llmd/results/exps/aristides/reason/${JOB_NAME}_${TIMESTAMP}}

VLLM_ENV=${VLLM_ENV:-vllm-env}
EVAL_ENV=${EVAL_ENV:-pipeline-rl}
MODEL_NAME=${MODEL_NAME:-openai/gpt-oss-120b}
HOST=${HOST:-127.0.0.1}
PORT=${PORT:-8380}
CUDA_DEVICES=${CUDA_DEVICES:-}
TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE:-4}
MAX_MODEL_LEN=${MAX_MODEL_LEN:-40000}
GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION:-0.9}
REASONING_LEVELS=${REASONING_LEVELS:-"low medium high"}
SUBSAMPLE=${SUBSAMPLE:-500}
TEST_MAX_SAMPLES=${TEST_MAX_SAMPLES:-500}
MAX_TOKENS=${MAX_TOKENS:-35000}
TEMPERATURE=${TEMPERATURE:-0.7}
SERVER_START_TIMEOUT_SECS=${SERVER_START_TIMEOUT_SECS:-900}

make job \
  JOB_NAME=${JOB_NAME}_${TIMESTAMP} \
  ENV=${EVAL_ENV} \
  CONDA_EXE=/opt/conda/bin/conda \
  SNAPSHOT=1 \
  NPROC=1 \
  GPU=4 \
  CPU=16 \
  CPU_MEM=256 \
  COMMAND="cd /home/toolkit/PipelineRL-SWE; mkdir -p ${OUTPUT_ROOT}; set -o pipefail; RUN_NAME=${JOB_NAME}_${TIMESTAMP} OUTPUT_ROOT=${OUTPUT_ROOT} VLLM_ENV=${VLLM_ENV} EVAL_ENV=${EVAL_ENV} MODEL_NAME=${MODEL_NAME} HOST=${HOST} PORT=${PORT} CUDA_DEVICES=${CUDA_DEVICES} TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE} MAX_MODEL_LEN=${MAX_MODEL_LEN} GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION} REASONING_LEVELS='${REASONING_LEVELS}' SUBSAMPLE=${SUBSAMPLE} TEST_MAX_SAMPLES=${TEST_MAX_SAMPLES} MAX_TOKENS=${MAX_TOKENS} TEMPERATURE=${TEMPERATURE} SERVER_START_TIMEOUT_SECS=${SERVER_START_TIMEOUT_SECS} bash /home/toolkit/PipelineRL-SWE/run_gpt_oss_reasoning_smoke_single_node_inner.sh 2>&1 | tee -a ${OUTPUT_ROOT}/launch.out"
