"""Frozen 100-per-dataset Jev success prediction pilot, $1 cumulative guard.
No target-model generations. Training aggregate route priors only in API state.
"""
import argparse,asyncio,fcntl,hashlib,json,math,time
from pathlib import Path
import sys
import numpy as np
import aiohttp
sys.path.insert(0,str(Path(__file__).resolve().parent))
from carrot_compare import POOLS,read_predictions,curve_arrays,compare_pair
from decompose import R,MK

MODEL='typesafe/jev-1.13'
ENDPOINT='https://openrouter.ai/api/alpha/decisions'
RATE=.042/1e6
ROUTES={'oss20lo':'OpenAI gpt-oss-20b, low reasoning effort',
        'oss20md':'OpenAI gpt-oss-20b, medium reasoning effort',
        'dsv4f':'DeepSeek deepseek-v4-flash, reasoning enabled',
        'oss120md':'OpenAI gpt-oss-120b, medium reasoning effort',
        'oss120hi':'OpenAI gpt-oss-120b, high reasoning effort'}
GRADING={'LCB':'Generate a complete programming solution that passes all hidden tests.',
         'Omni':'Solve the mathematics problem and return the correct final answer.',
         'MMLU-Pro':'Select the single correct multiple-choice answer.'}


def load_pool(label):
    name,costfile=POOLS[label];folder=R/name
    t=np.load(folder/'tensors.npz',allow_pickle=True)
    ids=[str(x) for x in t['problem_ids']];slots=[str(x) for x in t['model_slots']];pi={p:i for i,p in enumerate(ids)}
    sp=json.loads((folder/'split_manifest.json').read_text())
    tr=np.asarray([pi[str(x)] for x in sp['train_problem_ids']]);te=np.asarray([pi[str(x)] for x in sp['test_problem_ids']])
    v=t['valid'].astype(bool);n=v.sum(2)
    if not (n>0).all():raise ValueError('Missing route generation labels')
    q=np.where(v,t['final_outcome'],0).sum(2)/n
    length=np.where(v,t['completion_tokens'],0).sum(2)/n
    inp=np.where(v,t['prompt_tokens'],0).sum(2)/n
    rates=dict(MK)
    if (folder/'prices.json').exists():rates.update(json.loads((folder/'prices.json').read_text()))
    pin=np.asarray([rates[s][0] for s in slots])/1e6;pout=np.asarray([rates[s][1] for s in slots])/1e6
    paid=(inp*pin+length*pout)*100
    median=np.asarray([np.median(t['completion_tokens'][tr,j][v[tr,j]]) for j in range(len(slots))])
    med=(inp*pin+median*pout)*100
    p=read_predictions(folder/'content_preds.jsonl',ids,'p_successes',len(slots))
    cost=read_predictions(folder/costfile,ids,'expected_costs',len(slots))*100
    meta={str(r['problem_id']):r for r in map(json.loads,(folder/'problems.jsonl').open())}
    return dict(ids=ids,slots=slots,tr=tr,te=te,q=q,p=p,cost=cost,paid=paid,median=med,meta=meta,length=length,inp=inp,pin=pin,pout=pout)


def prepare(a):
    a.out.mkdir(parents=True,exist_ok=True)
    manifest=a.out/'manifest.json'
    if manifest.exists():
        d=json.loads(manifest.read_text())
        if d['n_per_pool']!=a.n or d['seed']!=a.seed or d['model']!=MODEL:
            raise ValueError('Existing frozen manifest differs from requested plan')
        return d
    rng=np.random.default_rng(a.seed);requests=[]
    for label in POOLS:
        d=load_pool(label);selected=rng.choice(d['te'],size=min(a.n,len(d['te'])),replace=False)
        priors=d['q'][d['tr']].mean(0)
        questions={s:{'type':'noul','instructions':
          f"Will one independent answer generated by the route described in `routes.{s}` correctly solve `problem` under `grading_rule`? Estimate this route's probability of correctness on this particular problem. The supplied training accuracy is a prior over other problems, not the answer for this problem. Do not assume an answer has already been generated.",
          'criteria':{'true':'The generated answer meets the grading rule completely.',
                      'false':'The generated answer fails the grading rule.'}} for s in d['slots']}
        for i in selected:
            state={'problem':str(d['meta'][d['ids'][i]]['problem_statement']),
                   'grading_rule':GRADING[label],
                   'routes':{s:{'description':ROUTES[s],
                                'training_accuracy':round(float(priors[j]),4)} for j,s in enumerate(d['slots'])}}
            body={'model':MODEL,'state':state,'questions':questions}
            requests.append({'pool':label,'problem_id':d['ids'][i],'model_slots':d['slots'],'body':body})
    # Freeze IDs and actual request payloads before the first paid request.
    encoded=json.dumps(requests,ensure_ascii=False,sort_keys=True)
    result={'model':MODEL,'endpoint':ENDPOINT,'n_per_pool':a.n,'seed':a.seed,
            'request_sha256':hashlib.sha256(encoded.encode()).hexdigest(),'requests':requests,
            'protocol':'Five correctness nouls in one call. Problem text, grading rule and training-only aggregate accuracy priors; no gold answers, generated answers, individual training examples or test outcomes. Fixed prompt; original test subset selected without labels.'}
    manifest.write_text(json.dumps(result,indent=2,ensure_ascii=False)+'\n')
    return result


def parse_response(response,slots):
    answers=response['answers'];values=[]
    for slot in slots:
        answer=answers[slot]
        if answer.get('type')!='noul':raise ValueError('Unexpected Jev answer type')
        p=answer.get('noul')
        if not isinstance(p,(int,float)) or not math.isfinite(p) or not 0<=p<=1:
            raise ValueError('Invalid Jev success probability')
        values.append(float(p))
    return values


async def collect(a,manifest,response_parser=parse_response,value_key="p_successes"):
    lock=(a.out/'collector.lock').open('w');fcntl.flock(lock,fcntl.LOCK_EX|fcntl.LOCK_NB)
    path=a.out/'responses.jsonl';done=set();spent=0.
    if path.exists():
        for r in map(json.loads,path.open()):
            spent+=r['charged_usd']
            if r['status']=='ok':done.add((r['pool'],r['problem_id']))
    key=Path(a.api_key_file).read_text().strip()
    pending=[r for r in manifest['requests'] if (r['pool'],r['problem_id']) not in done]
    print(json.dumps({'event':'start','pending':len(pending),'existing_spend':spent}),flush=True)
    if a.limit:
        pending=pending[:a.limit]
    queue=asyncio.Queue()
    for request in pending:queue.put_nowait(request)
    condition=asyncio.Condition();reserved=0.;errors=0;stopped=False;completed=0
    ceiling=64000*RATE
    with path.open('a') as logfile:
        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=120)) as session:
            async def worker():
                nonlocal spent,reserved,errors,stopped,completed
                while not queue.empty() and not stopped:
                    request=queue.get_nowait()
                    for attempt in range(3):
                        async with condition:
                            while spent+reserved+ceiling>a.budget_usd and reserved>0 and not stopped:
                                await condition.wait()
                            if stopped or spent+reserved+ceiling>a.budget_usd:
                                stopped=True;condition.notify_all();return
                            reserved+=ceiling
                        started=time.time();response={};status='error';probabilities=None;retry=False
                        error=None;http_status=None
                        try:
                            async with session.post(ENDPOINT,json=request['body'],headers={'Authorization':'Bearer '+key}) as result:
                                http_status=result.status
                                response=await result.json(content_type=None)
                                if result.status!=200:
                                    error='HTTP '+str(result.status)
                                    retry=result.status==429 or result.status>=500
                                else:
                                    probabilities=response_parser(response,request['model_slots']);status='ok'
                        except (aiohttp.ClientError,asyncio.TimeoutError) as exc:
                            error=type(exc).__name__;retry=True
                        except (ValueError,KeyError,TypeError) as exc:
                            error='Response schema: '+type(exc).__name__
                        usage=response.get('usage',{}) if isinstance(response,dict) else {}
                        cost=usage.get('cost')
                        # Unknown/ambiguous billing is charged at the max request cost
                        # for the guard; successful calls must report actual usage.
                        if cost is None:
                            cost=ceiling
                            if status=='ok':
                                status='error';error='Missing usage.cost';probabilities=None
                        if not isinstance(cost,(int,float)) or not math.isfinite(cost) or cost<0:
                            cost=ceiling;status='error';error='Invalid usage.cost';probabilities=None
                        row={'pool':request['pool'],'problem_id':request['problem_id'],'status':status,
                             'attempt':attempt+1,value_key:probabilities,'charged_usd':float(cost),
                             'elapsed_seconds':time.time()-started,'http_status':http_status,'error':error,
                             'model':response.get('model') if isinstance(response,dict) else None,
                             'response':response}
                        logfile.write(json.dumps(row)+'\n');logfile.flush()
                        async with condition:
                            spent+=float(cost);reserved-=ceiling
                            if status=='ok':completed+=1;done.add((request['pool'],request['problem_id']))
                            else:errors+=1
                            if errors>=10:stopped=True
                            condition.notify_all()
                        if status=='ok' or not retry or stopped:break
                        await asyncio.sleep(min(8,2**attempt))
                    queue.task_done()
                    if completed%25==0 or status!='ok':
                        print(json.dumps({'completed_this_run':completed,'errors':errors,'guard_spend_usd':spent}),flush=True)
            await asyncio.gather(*[worker() for _ in range(a.concurrency)])
    summary={'valid_calls':len(done),'expected_calls':len(manifest['requests']),
             'guard_spend_usd':spent,'complete':len(done)==len(manifest['requests']),
             'errors_this_run':errors,'budget_or_error_stop':stopped}
    (a.out/'collection_status.json').write_text(json.dumps(summary,indent=2)+'\n')
    print(json.dumps(summary),flush=True)
    lock.close()
    return summary


def analyze(a,manifest):
    rows={}
    for row in map(json.loads,(a.out/'responses.jsonl').open()):
        if row['status']=='ok':rows[row['pool'],row['problem_id']]=row
    report={}
    for label in POOLS:
        d=load_pool(label)
        selected=[r['problem_id'] for r in manifest['requests'] if r['pool']==label]
        index={p:i for i,p in enumerate(d['ids'])};ii=np.asarray([index[p] for p in selected])
        if any((label,p) not in rows for p in selected):raise ValueError('Pilot incomplete')
        pj=d['p'].copy()
        pj[ii]=np.asarray([rows[label,p]['p_successes'] for p in selected])
        priors=np.broadcast_to(d['q'][d['tr']].mean(0),d['p'].shape)
        # Same per-route median TRAIN output length for every success estimator.
        # Exactly known input costs retained, matching the paper's constant-cost control.
        arms={'ours':d['p'],'jev':pj,'training_base_rate':priors}
        curves={k:curve_arrays(p,d['median'],d['q'],d['paid'],ii) for k,p in arms.items()}
        rng=np.random.default_rng(0);resamples=[rng.integers(0,len(ii),len(ii)) for _ in range(1000)]
        contrasts={}
        for left,right in [('jev','ours'),('ours','jev'),('jev','training_base_rate')]:
            point,band=compare_pair(curves,left,right,np.arange(len(ii)))
            boot=np.asarray([compare_pair(curves,left,right,b)[0] for b in resamples]);finite=np.isfinite(boot)
            contrasts[left+'_vs_'+right]={'direct_cost_saved':point,'band':band,
                 'ci95':np.percentile(boot[finite],[2.5,97.5]).tolist() if finite.any() else None,
                 'valid_bootstrap':int(finite.sum()),'bootstrap':boot.tolist()}
        metrics={}
        for name,p in arms.items():
            pp=np.clip(p[ii],1e-6,1-1e-6);q=d['q'][ii]
            metrics[name]={'expected_draw_brier':float(np.mean(pp**2-2*pp*q+q)),
                          'expected_draw_logloss':float(-np.mean(q*np.log(pp)+(1-q)*np.log(1-pp))),
                          'mean_predicted_success':float(pp.mean()),'mean_observed_success':float(q.mean()),
                          'route_brier':dict(zip(d['slots'],map(float,(pp**2-2*pp*q+q).mean(0))))}
        report[label]={'n_test':len(ii),'problem_ids':selected,'metrics':metrics,'contrasts':contrasts}
        print(label,json.dumps({'metrics':metrics,'contrasts':{k:{x:y for x,y in v.items() if x!='bootstrap'} for k,v in contrasts.items()}}),flush=True)
    result={'model':MODEL,'request_sha256':manifest['request_sha256'],'pools':report,
            'protocol':'Exploratory frozen 100-per-pool test subsets. Training aggregate priors in prompt. No calibration or prompt selection. Same median training output length pricing for every success estimator. All valid stored generation draws. Paired problem bootstrap conditional on predictions; descriptive pair-specific convex-hull frontiers; no new target generations. Jev API cost reported separately from target generation spend.'}
    (a.out/'results.json').write_text(json.dumps(result,indent=2)+'\n')


def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--out',type=Path,default=Path('analysis/cost_headroom/jev_pilot_20261001'))
    ap.add_argument('--n',type=int,default=100)
    ap.add_argument('--seed',type=int,default=20261001)
    ap.add_argument('--budget-usd',type=float,default=1)
    ap.add_argument('--concurrency',type=int,default=8)
    ap.add_argument('--api-key-file',default='/home/toolkit/.secrets/openrouter_api_key')
    ap.add_argument('--limit',type=int,default=0,help='Limit newly attempted problems for an API smoke check')
    ap.add_argument('--prepare-only',action='store_true')
    ap.add_argument('--analyze-only',action='store_true')
    a=ap.parse_args()
    if min(a.n,a.budget_usd,a.concurrency)<=0 or a.limit<0:ap.error('Invalid counts/budget')
    manifest=prepare(a)
    if a.prepare_only:return
    if a.analyze_only:analyze(a,manifest);return
    result=asyncio.run(collect(a,manifest))
    if result['complete']:analyze(a,manifest)
    elif not a.limit:raise RuntimeError('Incomplete Jev pilot; inspect status before resuming')

if __name__=='__main__':main()
