"""Worked examples for "the readout reads work, not only difficulty" (TMLR sec:mechanism; NEW_PATH 4.A.81). Per pool, on TEST problems:
the readout's predicted log-length level (mean over the five routes, fitted on train) residualised on the five routes' TRUE solve rates
(+ squares): r > 0 = predicted LONG for its difficulty, r < 0 = SHORT for its difficulty. Writes a markdown report with
  (a) per subject / task / platform: mean r, mean actual log-length residual (same residualisation), n -- which kinds of question
      are long or short for their difficulty, and whether the readout agrees with reality;
  (b) the 6 problems with the largest and smallest r that ALL routes solve (difficulty cannot tell them apart), with solve rate,
      actual and predicted mean output tokens, and the first 300 characters of the question.
Usage: REASON_ROOT=.../reason_pinned OUT_DIR=... python worked_examples.py
"""
import json, os, sys
from pathlib import Path
import numpy as np
sys.path.insert(0, str(Path(__file__).parent))
_src = open(Path(__file__).parent / "cost_generalization.py").read()
exec(_src.split('MODE, POOL = sys.argv[1], sys.argv[2]')[0])
REAL = Path("/mnt/llmd/results/exps/aristides/reason"); OUT = Path(os.environ.get("OUT_DIR", Path(__file__).parent))
meta = {}
for f in [*REAL.glob("math_pool/*/problems.jsonl"), *Path(__file__).parent.glob("expansion_20261001/*_tasks*.jsonl")]:
    for l in open(f):
        if l.strip():
            r = json.loads(l); meta.setdefault(str(r["problem_id"]), r)


def resid(y, X):
    A = np.c_[np.ones(len(X)), X]; return y - A @ np.linalg.lstsq(A, y, rcond=None)[0]


md = ["# Worked examples: length beyond difficulty (generated by worked_examples.py)\n",
      "r = predicted log-length level residualised on the five routes' true solve rates; actual = the same for the realized mean "
      "log length. Positive: long for its difficulty.\n"]
for P_ in ("MMLU-Pro", "SuperGPQA", "BBEH", "LCB", "Omni", "AIME"):
    d = load(P_); N = len(d["ids"]); ev = d["ev"]
    name, _, ds = POOLS[P_]
    for f in [R / name / "problems.jsonl"] + ([R / "expanded_eval_20261001" / ds / "problems.jsonl"] if ds else []):
        if f.exists():
            for l in open(f):
                if l.strip():
                    x = json.loads(l); meta.setdefault(str(x["problem_id"]), x)
    lp = np.log(fit_predict("ours", view(d, d["tr"]), view(d, np.arange(N))))
    q = d["q"][ev]; D = np.c_[q, q ** 2]; lvl_p = lp[ev].mean(1); lvl_a = np.log(d["L"][ev]).mean(1)
    r_, a_ = resid(lvl_p, D), resid(lvl_a, D)
    ids = [d["ids"][i] for i in ev]; text = [str(meta.get(p, {}).get("problem_statement") or meta.get(p, {}).get("problem") or "") for p in ids]
    grp = [str(meta.get(p, {}).get("subject") or meta.get(p, {}).get("platform") or p.split("_")[0]) for p in ids]
    md.append(f"\n## {P_} (test {len(ev)}; corr(r, actual residual) = {np.corrcoef(r_, a_)[0, 1]:+.2f})\n")
    md.append("| group | n | mean r (predicted) | mean actual residual |\n|---|---|---|---|")
    g_ = sorted(set(grp), key=lambda g: -np.mean(r_[np.array(grp) == g]))
    for g in g_:
        m = np.array(grp) == g
        if m.sum() >= 8:
            md.append(f"| {g} | {m.sum()} | {r_[m].mean():+.2f} | {a_[m].mean():+.2f} |")
    solved = np.where((q == 1).all(1))[0]
    if len(solved) >= 12:
        o = solved[np.argsort(r_[solved])]
        for title, sel in (("Predicted LONG for their difficulty (every route solves them)", o[::-1][:6]),
                           ("Predicted SHORT for their difficulty (every route solves them)", o[:6])):
            md.append(f"\n**{title}**\n")
            md.append("| id | group | actual mean tokens | predicted mean tokens | question (first 300 chars) |\n|---|---|---|---|---|")
            for i in sel:
                t = text[i][:300].replace("|", "/").replace("\n", " ")
                md.append(f"| {ids[i]} | {grp[i]} | {np.exp(lvl_a[i]):.0f} | {np.exp(lvl_p[i]):.0f} | {t} |")
    print(f"{P_}: corr(r, actual residual) {np.corrcoef(r_, a_)[0, 1]:+.2f}; all-solved {len(solved)}", flush=True)
(OUT / "worked_examples.md").write_text("\n".join(md) + "\n")
print("DONE", flush=True)
